### ISSUE TITLE
Image upload cancellation hangs the tool

### ISSUE THREAD

**Issue by AagamShah97** [nanoMFG/GSAMain#121]
The service used to upload any files to a tool on nanoHUB hangs the tool if the process is cancelled (using the cross on the top right corner). The issue is caused because the file upload widget needs to return some value for the tool to unfreeze.

![Image-1.png](https://images.zenhubusercontent.com/5d96d48455905700018a4938/d4cee9e8-523f-4c19-b686-3745ec30f4a3)

[gresq.log](https://app.zenhub.com/files/152770945/c5dc550e-6f80-4c2e-b6c5-e80660fb4587/download)
[filexfer657.log](https://app.zenhub.com/files/152770945/e7a8568f-aa33-4783-9609-350e0d4a2465/download)

**Comment by dadamsncsa** [comment]
nanoHUB updated their default libraries to include a "cancel" button.  Which seems to work.
